//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Secretary.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthCare.View.Secretary.Properties2.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About the patient.
        /// </summary>
        public static string aboutThePatient {
            get {
                return ResourceManager.GetString("aboutThePatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abscence requests.
        /// </summary>
        public static string abscenceRequests {
            get {
                return ResourceManager.GetString("abscenceRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add article.
        /// </summary>
        public static string addArticle {
            get {
                return ResourceManager.GetString("addArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add photo.
        /// </summary>
        public static string addPhoto {
            get {
                return ResourceManager.GetString("addPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add question.
        /// </summary>
        public static string addQuestion {
            get {
                return ResourceManager.GetString("addQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }

        public static string dateError
        {
            get
            {
                return ResourceManager.GetString("dateError", resourceCulture);
            }
        }

        public static string vreme
        {
            get
            {
                return ResourceManager.GetString("vreme", resourceCulture);
            }
        }

        public static string back
        {
            get
            {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        public static string addfaq
        {
            get
            {
                return ResourceManager.GetString("addfaq", resourceCulture);
            }
        }
        
        public static string error
        {
            get
            {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        public static string reportError
        {
            get
            {
                return ResourceManager.GetString("reportError", resourceCulture);
            }
        }

        public static string numberError
        {
            get
            {
                return ResourceManager.GetString("numberError", resourceCulture);
            }
        }
        public static string zipError
        {
            get
            {
                return ResourceManager.GetString("zipError", resourceCulture);
            }
        }
        public static string jmbgError
        {
            get
            {
                return ResourceManager.GetString("jmbgError", resourceCulture);
            }
        }
        public static string timeError
        {
            get
            {
                return ResourceManager.GetString("timeError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        public static string appointment {
            get {
                return ResourceManager.GetString("appointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointments.
        /// </summary>
        public static string appointments {
            get {
                return ResourceManager.GetString("appointments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string approved {
            get {
                return ResourceManager.GetString("approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string article {
            get {
                return ResourceManager.GetString("article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biography.
        /// </summary>
        public static string biography {
            get {
                return ResourceManager.GetString("biography", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth date.
        /// </summary>
        public static string birhdate {
            get {
                return ResourceManager.GetString("birhdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog.
        /// </summary>
        public static string blog {
            get {
                return ResourceManager.GetString("blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }

        public static string cancelQuestion
        {
            get
            {
                return ResourceManager.GetString("cancelQustion", resourceCulture);
            }
        }
        public static string appointmentChooseDate
        {
            get
            {
                return ResourceManager.GetString("appointmentChooseDate", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Change photo.
        /// </summary>
        public static string changePhoto {
            get {
                return ResourceManager.GetString("changePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose appointment date.
        /// </summary>
        public static string chooseAppointmentDate {
            get {
                return ResourceManager.GetString("chooseAppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose date for details.
        /// </summary>
        public static string chooseDateForDetails {
            get {
                return ResourceManager.GetString("chooseDateForDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose new appointment date.
        /// </summary>
        public static string chooseNewAppointmentDate {
            get {
                return ResourceManager.GetString("chooseNewAppointmentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose new surgery date.
        /// </summary>
        public static string chooseNewOperationDate {
            get {
                return ResourceManager.GetString("chooseNewOperationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose start and end date of patient tretmant.
        /// </summary>
        public static string chooseStartEndDate {
            get {
                return ResourceManager.GetString("chooseStartEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose surgery date.
        /// </summary>
        public static string chooseSurgeryDate {
            get {
                return ResourceManager.GetString("chooseSurgeryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string confirmation {
            get {
                return ResourceManager.GetString("confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day details.
        /// </summary>
        public static string dateDetails {
            get {
                return ResourceManager.GetString("dateDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   Days Left: 10.
        /// </summary>
        public static string daysLeft {
            get {
                return ResourceManager.GetString("daysLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days off.
        /// </summary>
        public static string daysOff {
            get {
                return ResourceManager.GetString("daysOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor.
        /// </summary>
        public static string doctor {
            get {
                return ResourceManager.GetString("doctor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor replies.
        /// </summary>
        public static string doctorReply {
            get {
                return ResourceManager.GetString("doctorReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string duration {
            get {
                return ResourceManager.GetString("duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit appointment.
        /// </summary>
        public static string editAppointment {
            get {
                return ResourceManager.GetString("editAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit profile.
        /// </summary>
        public static string editprofile {
            get {
                return ResourceManager.GetString("editprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string faq {
            get {
                return ResourceManager.GetString("faq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string first {
            get {
                return ResourceManager.GetString("first", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string from {
            get {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gray.
        /// </summary>
        public static string gray {
            get {
                return ResourceManager.GetString("gray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string lang {
            get {
                return ResourceManager.GetString("lang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light blue.
        /// </summary>
        public static string light_blue {
            get {
                return ResourceManager.GetString("light-blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string logout {
            get {
                return ResourceManager.GetString("logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main page.
        /// </summary>
        public static string mainpage {
            get {
                return ResourceManager.GetString("mainpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make an appointment.
        /// </summary>
        public static string makeAnAppointment {
            get {
                return ResourceManager.GetString("makeAnAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make PDF.
        /// </summary>
        public static string makePDF {
            get {
                return ResourceManager.GetString("makePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical record number.
        /// </summary>
        public static string medicalRecord {
            get {
                return ResourceManager.GetString("medicalRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More info.
        /// </summary>
        public static string moreInfo {
            get {
                return ResourceManager.GetString("moreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        public static string move {
            get {
                return ResourceManager.GetString("move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move appointment.
        /// </summary>
        public static string moveAppointment {
            get {
                return ResourceManager.GetString("moveAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string notification {
            get {
                return ResourceManager.GetString("notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string notifications {
            get {
                return ResourceManager.GetString("notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgery.
        /// </summary>
        public static string operation {
            get {
                return ResourceManager.GetString("operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgeries.
        /// </summary>
        public static string operations {
            get {
                return ResourceManager.GetString("operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patinet.
        /// </summary>
        public static string patient {
            get {
                return ResourceManager.GetString("patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient moving.
        /// </summary>
        public static string patientMoving {
            get {
                return ResourceManager.GetString("patientMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string patientrequests {
            get {
                return ResourceManager.GetString("patientrequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient tretmant.
        /// </summary>
        public static string patientTretmant {
            get {
                return ResourceManager.GetString("patientTretmant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string phonenumber {
            get {
                return ResourceManager.GetString("phonenumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place.
        /// </summary>
        public static string place {
            get {
                return ResourceManager.GetString("place", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        public static string profil {
            get {
                return ResourceManager.GetString("profil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string question {
            get {
                return ResourceManager.GetString("question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string report {
            get {
                return ResourceManager.GetString("report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day of the week for which you need the report.
        /// </summary>
        public static string reportDay1 {
            get {
                return ResourceManager.GetString("reportDay1", resourceCulture);
            }
        }

        public static string reportDay2
        {
            get
            {
                return ResourceManager.GetString("reportDay2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Report type.
        /// </summary>
        public static string reportType {
            get {
                return ResourceManager.GetString("reportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string request {
            get {
                return ResourceManager.GetString("request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request type.
        /// </summary>
        public static string requestType {
            get {
                return ResourceManager.GetString("requestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response.
        /// </summary>
        public static string response {
            get {
                return ResourceManager.GetString("response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string room {
            get {
                return ResourceManager.GetString("room", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        public static string rooms {
            get {
                return ResourceManager.GetString("rooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room type.
        /// </summary>
        public static string roomType {
            get {
                return ResourceManager.GetString("roomType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string second {
            get {
                return ResourceManager.GetString("second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sector.
        /// </summary>
        public static string sector {
            get {
                return ResourceManager.GetString("sector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send request.
        /// </summary>
        public static string sendRequest {
            get {
                return ResourceManager.GetString("sendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set surgery date.
        /// </summary>
        public static string setSurgeryDate {
            get {
                return ResourceManager.GetString("setSurgeryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing language will require app to restart. Are you sure you want to continue?.
        /// </summary>
        public static string settingsQuestion {
            get {
                return ResourceManager.GetString("settingsQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shift.
        /// </summary>
        public static string shift {
            get {
                return ResourceManager.GetString("shift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sick leave.
        /// </summary>
        public static string sickLeave {
            get {
                return ResourceManager.GetString("sickLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serbian.
        /// </summary>
        public static string sr {
            get {
                return ResourceManager.GetString("sr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgery moving.
        /// </summary>
        public static string surgeryMoving {
            get {
                return ResourceManager.GetString("surgeryMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgery schedule overview.
        /// </summary>
        public static string surgeryOverview {
            get {
                return ResourceManager.GetString("surgeryOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string surname {
            get {
                return ResourceManager.GetString("surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string theme {
            get {
                return ResourceManager.GetString("theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string time {
            get {
                return ResourceManager.GetString("time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow white.
        /// </summary>
        public static string yellow_white {
            get {
                return ResourceManager.GetString("yellow-white", resourceCulture);
            }
        }
    }
}
